NetworkMarketing/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import Homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Homepage, name='home'),
    path('accounts/', include('accounts.urls')),
    path('management/', include('management.urls')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (LoginView, LogoutView, LogoutView)

from .views import AccountCreation, Payment, login,UpdateProfile

app_name = 'accounts'

urlpatterns = [
    path('signup/', AccountCreation.as_view(), name='signup'),
    path('payment/', Payment.as_view(), name='payment'),
    # path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('login/', login, name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/login.html'), name='logout'),
    # path('change_password/', change_password, name='change_password'),
    path('update/<pk>',UpdateProfile.as_view(),name='update-profile'),
]

management/urls.py
from django.urls import path

from .views import Profile,ListOfUser,ApproveList,DeleteUser,approveUser

app_name = 'management'

urlpatterns = [
    path('profile/', Profile.as_view(), name='profile'),
    path('user-list/', ListOfUser.as_view(), name='user-list'),
    path('approve/',ApproveList.as_view(),name='approve'),
    path('delete/<pk>',DeleteUser.as_view(),name='delete'),

    path('approve-user/<pk>',approveUser,name='approve-user')
]

management/models.py
from django.db import models

from accounts.models import Accounts

management/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from accounts.models import Accounts


class Profile(LoginRequiredMixin, ListView):
    paginate_by = 5

    def get_queryset(self):
        query = Accounts.objects.filter(parent_id=self.request.user.id)
        return query

    def get_template_names(self):
        if self.request.user.is_admin:
            return 'management/admin_profile.html'
        else:
            return 'management/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_user'] = Accounts.objects.filter(is_active=True).count()
        context['total_user'] = Accounts.objects.all().count()
        context['pending_user'] = context['total_user'] - context['active_user']

        context['parent'] = Accounts.objects.get(id=self.request.user.parent_id)
        return context


class ListOfUser(LoginRequiredMixin, ListView):
    queryset = Accounts.objects.all()
    template_name = 'management/user_list.html'


class ApproveList(LoginRequiredMixin, ListView):
    paginate_by = 10
    template_name = 'management/approve_list.html'
    queryset = Accounts.objects.filter(is_active=False)


class DeleteUser(LoginRequiredMixin, DeleteView):
    model = Accounts
    success_url = reverse_lazy('management:approve')
    template_name = 'management/delete.html'



@login_required
def approveUser(request, pk):
    user = get_object_or_404(Accounts, id=pk)
    user.activate_user()
    return redirect('management:approve')

management/templates/management/Edit.html
<div class="container">
		<div class="main-body">
			<div class="row">
				<div class="col-lg-4">
					<div class="card">
						<div class="card-body">
							<div class="d-flex flex-column align-items-center text-center">
								<img src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="Admin" class="rounded-circle p-1 bg-primary" width="110">
								<div class="mt-3">
									<h4>John Doe</h4>
									<p class="text-secondary mb-1">Full Stack Developer</p>
									<p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p>
									<button class="btn btn-primary">Follow</button>
									<button class="btn btn-outline-primary">Message</button>
								</div>
							</div>
							<hr class="my-4">
							<ul class="list-group list-group-flush">
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe me-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
									<span class="text-secondary">https://bootdey.com</span>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github me-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
									<span class="text-secondary">bootdey</span>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter me-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
									<span class="text-secondary">@bootdey</span>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram me-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
									<span class="text-secondary">bootdey</span>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook me-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
									<span class="text-secondary">bootdey</span>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-8">
					<div class="card">
						<div class="card-body">
							<div class="row mb-3">
								<div class="col-sm-3">
									<h6 class="mb-0">Full Name</h6>
								</div>
								<div class="col-sm-9 text-secondary">
									<input type="text" class="form-control" value="John Doe">
								</div>
							</div>
							<div class="row mb-3">
								<div class="col-sm-3">
									<h6 class="mb-0">Email</h6>
								</div>
								<div class="col-sm-9 text-secondary">
									<input type="text" class="form-control" value="john@example.com">
								</div>
							</div>
							<div class="row mb-3">
								<div class="col-sm-3">
									<h6 class="mb-0">Phone</h6>
								</div>
								<div class="col-sm-9 text-secondary">
									<input type="text" class="form-control" value="(239) 816-9029">
								</div>
							</div>
							<div class="row mb-3">
								<div class="col-sm-3">
									<h6 class="mb-0">Mobile</h6>
								</div>
								<div class="col-sm-9 text-secondary">
									<input type="text" class="form-control" value="(320) 380-4539">
								</div>
							</div>
							<div class="row mb-3">
								<div class="col-sm-3">
									<h6 class="mb-0">Address</h6>
								</div>
								<div class="col-sm-9 text-secondary">
									<input type="text" class="form-control" value="Bay Area, San Francisco, CA">
								</div>
							</div>
							<div class="row">
								<div class="col-sm-3"></div>
								<div class="col-sm-9 text-secondary">
									<input type="button" class="btn btn-primary px-4" value="Save Changes">
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="card">
								<div class="card-body">
									<h5 class="d-flex align-items-center mb-3">Project Status</h5>
									<p>Web Design</p>
									<div class="progress mb-3" style="height: 5px">
										<div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p>Website Markup</p>
									<div class="progress mb-3" style="height: 5px">
										<div class="progress-bar bg-danger" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p>One Page</p>
									<div class="progress mb-3" style="height: 5px">
										<div class="progress-bar bg-success" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p>Mobile Template</p>
									<div class="progress mb-3" style="height: 5px">
										<div class="progress-bar bg-warning" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p>Backend API</p>
									<div class="progress" style="height: 5px">
										<div class="progress-bar bg-info" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

management/templates/management/admin_profile.html
{%  extends 'base.html' %}
{% block content %}
<div class="container">
  <br>
    <div class="main-body">
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h6 class="font-size-sm">{{ request.user.first_name }} {{ request.user.last_name }}</h6>
                      <p class="text-muted font-size-sm">Address: {{ request.user.address }}</p>
                      <a class="btn btn-primary" href="{% url 'accounts:update-profile' pk=request.user.id %}">Edit Profile</a>
                    </div>
                  </div>
                </div>
              </div>
                <div class="card text-white bg-dark mt-3" style="max-width: 22rem;">
                  <div class="card-header text-center">List of Total Member</div>
                  <div class="card-body">
                    <h5 class="card-title text-center">{{total_user}} Total users.</h5>
                  </div>
                </div>

                <div class="card text-white bg-success mt-3" style="max-width: 22rem;">
                  <div class="card-header text-center">List of Active Member</div>
                  <div class="card-body">
                    <h5 class="card-title text-center">{{active_user}} Active users.</h5>
                  </div>
                </div>

                <div class="card text-white bg-danger mt-3" style="max-width: 22rem;">
                  <div class="card-header text-center">List of Pending Member</div>
                  <div class="card-body">
                    <h5 class="card-title text-center">{{ pending_user }} Pending users.</h5>
                  </div>
                </div>
            </div>
              {% include 'management/user_detail.html' %}

              {% include 'management/child_data.html' %}

            </div>
          </div>

        </div>
    </div>
{% endblock %}

management/templates/management/approve_list.html
{%  extends 'base.html' %}
{% block content %}
    {% if user.is_admin %}
<br>
{% if object_list.count == 0 %}
    <div class="container text-center">
        <h4>No request pending...</h4>
    </div>

{% else %}
<table class="table table-sm">
    <thead>
    <tr>
      <th scope="col">Ds ID</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Mobile</th>
      <th scope="col">Email</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
    <tbody>
    {% for user in object_list %}
        <tr>
      <th scope="row"><a href="#">{{user.referral_code}}</a></th>
      <td>{{user.first_name}}</td>
      <td>{{user.last_name}}</td>
      <td>{{user.mobile}}</td>
      <td>{{user.email}}</td>
      <td>
          <a href="{% url 'management:approve-user' pk=user.id %}" class="btn btn-success">Approve</a>
          <a href="{% url 'management:delete' pk=user.id %}" class="btn btn-danger">Delete</a>
      </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}
    {% else %}
    {% include 'permission_denied.html' %}
    {% endif %}
{% endblock %}

management/templates/management/child_data.html
<div class="row gutters-sm">
                <div class="col-sm-12 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Members</i></h6>
                        {% if object_list.count == 0 %}
                            <p>No members found..</p>
                        {% else %}
                        <table class="table">
                            <thead>
                                <tr>
                                  <th scope="col">No.</th>
                                  <th scope="col">DS Id</th>
                                  <th scope="col">First</th>
                                  <th scope="col">Last</th>
                                  <th scope="col">Mobile</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in object_list %}
                                  <tr>
                                  <th scope="row">{{ forloop.counter }}</th>
                                  <td>{{user.referral_code}}</td>
                                  <td>{{user.first_name}}</td>
                                  <td>{{user.last_name}}</td>
                                  <td>{{user.mobile}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% endif %}
                    </div>
                  </div>
                </div>
              </div>

management/templates/management/delete.html
{%  extends 'base.html' %}
{% block content %}
<br>
<div class="card container" style="width: auto;float:left">
    <form method="POST">
        {% csrf_token %}
      <div class="card-body">
        <h5 class="card-title">Delete User</h5>
        <p class="card-text">Are you want to delete {{object.first_name}} {{object.last_name}} user?</p>
        <a href="{% url 'management:approve' %}" class="btn btn-warning">Go back</a>
        <button type="submit" class="btn btn-danger">Delete</button>
      </div>
    </form>
</div>
{% endblock %}

management/templates/management/profile.html
{%  extends 'base.html' %}

{% block content %}
<div class="container">
  <br>
    <div class="main-body">
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h6 class="font-size-sm">{{ request.user.first_name }} {{ request.user.last_name }}</h6>
                      <p class="text-muted font-size-sm">Address: {{ request.user.address }}</p>
                      <a class="btn btn-primary" href="{% url 'accounts:update-profile' pk=request.user.id %}">Edit profile</a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card text-white bg-secondary card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Parents Detail</h5>
                  <hr>
                  <h6>Name- {{ parent.first_name }} {{ parent.last_name }}</h6>
                  <h6>DS id- {{ parent.referral_code }}</h6>
                  <h6>Mobile- {{ parent.mobile }}</h6>
                  <h6>Email- {{ parent.email }}</h6>
                </div>
              </div>
            </div>
              {% include 'management/user_detail.html' %}

              {% include 'management/child_data.html' %}

            </div>
          </div>

        </div>
    </div>
{% endblock %}

management/templates/management/user_detail.html
<div class="col-md-8">
  <div class="card mb-3">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">First Name</h6>
        </div>
        <div class="col-sm-9 text-secondary">
            {{ request.user.first_name }}
        </div>
      </div>
      <hr>
        <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">Last Name</h6>
        </div>
        <div class="col-sm-9 text-secondary">
            {{ request.user.last_name }}
        </div>
      </div>
        <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">Email</h6>
        </div>
        <div class="col-sm-9 text-secondary">
            {{ request.user.email }}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">Mobile</h6>
        </div>
        <div class="col-sm-9 text-secondary">
            +91 {{ request.user.mobile }}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">Ds Id</h6>
        </div>
        <div class="col-sm-9 text-secondary fw-bolder">
          {{ request.user.referral_code }}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">Address</h6>
        </div>
        <div class="col-sm-9 text-secondary">
          {{ request.user.address }}
        </div>
      </div>
    </div>
  </div>

management/templates/management/user_list.html
{%  extends 'base.html' %}

{% block content %}
<br>
{% if user.is_admin %}
<table class="table table-striped">
  <thead>
    <th scope="col">No.</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Ds ID</td>
    <th>Mobile Number</td>
    <th>Action</th>
  </thead>
  <tbody>
  {% for user in object_list %}
    {% if not user.is_active %}
    <tr class="table-danger">
      {% else %}
      <tr class="table-success">
    {% endif %}
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{user.first_name}}</td>
      <td>{{user.last_name}}</td>
      <td>{{user.referral_code}}</td>
      <td>{{user.mobile}}</td>
    <td>
      <a href="#" class="btn btn-primary">Go to Profile</a>
    </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}
{% endblock %}